---
name: Build and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run stack
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run e2e:ci
